### ISSUE TITLE
How to add highlight text and font color?

### ISSUE THREAD

**Issue by Jupiter79** [Ghasel/streamlit-quill#1]
Hi,

First of all, thank you very much on the effort to adopt Quill to Streamlit, it is a great idea!
We would like to start implementing it in the app we created (of course, with reference to your code), but we would need options to highlight text, and to change font color in editor. Could you please tell me if there is such possibility in your Quill implementation, and how to apply it? Thank you once again!

Best regards,
Jovan

**Comment by Ghasel** [comment]
Hello @Jupiter79,

I've published a new version with a better toolbar configuration, which includes text highlight and font color.
If you want to further customize the toolbar (keep only what you need for instance), I forward you to [Quill's official documentation](https://quilljs.com/docs/modules/toolbar/).

The default toolbar configuration is set Python side like so:
```python
toolbar=[
    [
        'bold', 'italic', 'underline', 'strike',
        {'script': 'sub'},
        {'script': 'super'},
    ],
    [
        { 'background': []},
        { 'color': [] },
    ],          
    [
        { 'list': 'ordered'},
        { 'list': 'bullet' },
        { 'indent': '-1'},
        { 'indent': '+1' },
        { 'align': [] },
    ],
    [
        { 'header': 1 },
        { 'header': 2 },
        { 'header': [1, 2, 3, 4, 5, 6, False] },
    ],
    ['blockquote', 'code-block', "clean"],
    [
        { 'size': ['small', False, 'large', 'huge'] },
        { 'font': [] },
    ],
]
```

**Comment by Jupiter79** [comment]
Hi @Ghasel ,
Thank you very much, this was more than helpful!

Best,
Jovan
